HDFS_HOST = "namenode"
HDFS_PORT = 9000
DATA_PATH = f"hdfs://{HDFS_HOST}:{HDFS_PORT}/data"

BRONZE_DATA_PATH = f"{DATA_PATH}/bronze"

ACTORS_PATH = f"{BRONZE_DATA_PATH}/actors"

REPOS_PATH = f"{BRONZE_DATA_PATH}/repos"

GITHUB_EVENTS_PATH = f"{BRONZE_DATA_PATH}/github_events"

SILVER_PATH = f"{DATA_PATH}/silver"
