HDFS_HOST = "namenode"
HDFS_PORT = 9000
DATA_PATH = f"hdfs://{HDFS_HOST}:{HDFS_PORT}/data"

SILVER_DATA_PATH = f"{DATA_PATH}/silver"

ACTORS_PATH = f"{SILVER_DATA_PATH}/actors"

REPOS_PATH = f"{SILVER_DATA_PATH}/repos"

GITHUB_EVENTS_PATH = f"{SILVER_DATA_PATH}/github_events"
